title: Esnil Josue Guevara M. # your name (or website title) here
logo: "/images/visa c.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Soy licenciado en matemática con más de 7 años de experiencia aplicando métodos de aprendizaje estadístico. También poseo conocimientos avanzados en la interpretación de modelos de ML, en estadística, en optimización y en herramientas/lenguajes computacionales como Python y R. En estos últimos 4 años he adquirido experiencia en procesamiento de datos y en herramientas de Data Science.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/esnil-guevara-8506771a3/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
