title: Esnil Guevara # your name (or website title) here
logo: "/images/visa c.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Machine Learning Engineer con +7 años de experiencia
  <br><br>
  Data Scientist con +4 años de experiencia
  <br><br>
  <a href="https://www.linkedin.com/in/esnil-guevara-8506771a3/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
